[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.49.0",
    "pandas>=2.2.3",
    "psycopg2-binary>=2.9.10",
    "streamlit>=1.43.1",
    "trafilatura>=2.0.0",
]
